library(ggplot2)
library(catSurv)
library(scales)
library(dplyr)
library(plyr)
library(latex2exp)
library(purrr)
library(haven)
library(dplyr)
library(foreign)
library(catSurv)
library(readxl)
library(fuzzyjoin)
data<-read_sav("C:/Users/dl0ck/OneDrive/Documents/Summer 2018/Montgomery/catSurv_dl/big 5/raw_data/yougov.R" )
big5_type<-read_xlsx("C:/Users/dl0ck/OneDrive/Documents/Summer 2018/Montgomery/catSurv_dl/big 5/fb_yg/big5_type.xlsx" )

View(big5_type)
colnames(big5_type)<-c("question", "char")
yougov<- data %>%
  select(BIGFIVE_1:BIGFIVE_100)
class(ques[1])
dam<-as.data.frame(dam)
ques<-yougov %>% map_chr(~attributes(.)$label)
ques <-cbind(god, rownames(dam))
colnames(ques)<-c("question", "number")
ques<-as.data.frame(ques)
ques<-apply(ques, 1,function(i){gsub("Describe self:", "",i)})
rownames(yougov)
ques[3,1]<-"Don't mind being the center of attention."
big5_type[45,1]<- "Avoid contact with others"
big5_type<-as.data.frame(big5_type)
ques<-as.data.frame(ques)
View(big5_type)
View(ques)
tri<-inner_join(big5_type,ques)
class(big5_type[1,1])
class(god[1,1])
big5_type[,1]
god<-big5_type[1:100,1]
god<-as.data.frame(god)
god<-apply(big5_type, 1,function(x){as.character(x)})
god<-as.data.frame(god)

tri<-merge(big5_type, ques, by=c('question'))
View(tri)
rm(cat)
